# Generated by Django 2.1.5 on 2020-02-24 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=17)),
                ('sku', models.CharField(help_text='Enter Product Stock Keeping Unit', max_length=13)),
                ('quantity', models.FloatField(help_text='Enter Product Quantity')),
                ('discription', models.CharField(max_length=255)),
                ('created_date', models.TimeField(default=django.utils.timezone.now)),
                ('last_updated', models.TimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='app/')),
                ('buffer_stock', models.FloatField(help_text='Enter Product Quantity')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
